[cuda]
packages = ["cc_torch", "torch_generic_nms", "flash-attn", "sageattention"]

[node_reqs]
ComfyUI-VideoHelperSuite = "Kosinkadink/ComfyUI-VideoHelperSuite"
ComfyUI-Multiband = "PozzettiAndrea/ComfyUI-Multiband"
ComfyUI-Env-Manager = "PozzettiAndrea/ComfyUI-Env-Manager"